# MD013 - Line length
# https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md013.md
MD013: false
# MD033 - Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md033.md
MD033: false
# MD034 - Bare URL used
# https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md034.md
MD034: false
